import Footer from "../../components/Footer/Footer";
import Navbar from '../../components/Navbar/index'
import './termsOfUsePage.css'
function TermsOfUsePage() {
    return (
        <div className="container">
            <Navbar />
            <div className="content">
                <div className="termsOfUsePage">
                    <h1>TERMOS DE USO</h1>
                    <div className="text">
                    <p>Bem-vindo ao <span> https://www.portodevantagens.com.br!</span></p> 
<p>A seguir apresentamos os Termos e Condições de Uso (“Termos”), documento que relaciona as principais regras que devem ser observadas por todos que acessam o <span> https://www.portodevantagens.com.br</span> da <span> Porto rent a car responsável pelo site</span> ou utilizam suas funcionalidades (<span>  “Você” </span>). </p>
<p>Como condição para acesso e uso das funcionalidades do <span> https://www.portodevantagens.com.br , Você</span> declara que fez a leitura completa e atenta das regras deste documento, tomando plena ciência de seu conteúdo. </p>
<p>Se<span>  Você</span> estiver de acordo com as regras apresentadas, deverá se manifestar neste sentido ao cadastrar-se no <span> https://www.portodevantagens.com.br</span> , por meio da seleção da checkbox “Li, compreendi e concordo com os Termos de Uso do https://www.portodevantagens.com.br  ”, demonstrando seu consentimento livre, expresso e informado. </p>
<p>Caso <span> Você</span> discorde de alguma das previsões destes Termos, solicitamos que não acesse ou utilize os serviços do <span> https://www.portodevantagens.com.br</span> </p>

<h3> 1. FUNCIONALIDADES DO PORTODEVANTAGENS.COM.BR</h3>
<p><span> 1.1. Funcionalidade. </span> O <span>https://www.portodevantagens.com.br</span>  o site consiste em uma plataforma para que os usuários conheçam a Porto rent a car, obtenham informações sobre as particularidades do negócio e acessem documentos relevantes. </p>
<p><span> 1.2. Modo de Funcionamento do https://www.portodevantagens.com.br</span>  . Os usuários podem interagir com a Porto rent a car por meio do envio de mensagens no Fale Conosco . </p>
<p><span> 1.3. Maioridade. </span> O acesso e utilização do <span> https://www.portodevantagens.com.br</span>  é livre para todos, porém algumas funcionalidades como cadastros em determinados ambientes podem exigir atos praticados por maiores de 18 (dezoito) anos, conforme legislação em vigor. </p>
<p><span> 1.3.1. </span> Nestes casos, os representantes legais deverão supervisionar e representar as crianças e adolescentes com idade inferior a 16 (dezesseis) anos e assistir os adolescentes em idade superior à 16 (dezesseis) anos e inferior à 18 (dezoito) anos, sempre que aplicável. </p>
<p><span> 1.3.2</span>. A <span>Porto rent a car</span> poderá recusar, não aprovar, cancelar ou limitar quaisquer solicitações, caso Você não forneça dados corretos. </p>
<p><span> 1.3.3</span>. O mesmo será aplicável durante a utilização do <span> https://www.portodevantagens.com.br</span> , se o mesmo for utilizado de forma fraudulenta, bem como que tente ou viole estes Termos ou quaisquer legislações vigentes. </p>
<p><span> 1.4. Elegibilidade. A Porto rent a car</span> poderá alterar os critérios de elegibilidade de acesso e utilização do <span> https://www.portodevantagens.com.br</span>  a qualquer momento e a seu critério sem a necessidade de comunicação ou aviso prévio à <span> Você</span> ou qualquer terceiro. </p>
<p><span> 1.5. E-mails. </span> Ao fornecer seus dados no <span> https://www.portodevantagens.com.br , Você</span> concorda que poderá receber no e-mail e/ou telefone informados no cadastro, mensagens com avisos e conteúdo publicitário de produtos ou serviços da Porto rent a car e de seus parceiros. Através do próprio <span> https://www.portodevantagens.com.br  Você</span> terá sempre a opção de não receber tais comunicações. </p>
<p><span> 1.6. Apresentação do https://www.portodevantagens.com.br. </span> O <span> https://www.portodevantagens.com.br</span>  e suas funcionalidades são apresentadas a <span>Você </span>na maneira como estão disponíveis, podendo passar por constantes aprimoramentos e atualizações. </p>
<p><span>1.6.1. </span> Neste caso a Porto rent a car se compromete a preservar a funcionalidade do<span>  https://www.portodevantagens.com.br </span> com esforços razoáveis, com Links não quebrados e utilizando Layout que respeita a usabilidade e navegabilidade, sempre que possível, bem como exibir as funcionalidades de maneira clara, completa, precisa e suficiente de modo que exista uma correta percepção do que está sendo praticado. </p>

<h3> 2. USO DO PORTODEVANTAGENS.COM.BR</h3>

<p><span> 2.1. Integridade do https://www.portodevantagens.com.br . Você</span> se compromete a não acessar áreas de programação do <span> https://www.portodevantagens.com.br</span>  , seu banco de dados, códigos fonte ou qualquer outro conjunto de dados disponíveis estes ambientes, bem como não realizar ou permitir engenharia reversa, nem traduzir, decompilar, copiar, modificar, reproduzir, alugar, sublicenciar, publicar, divulgar, transmitir, emprestar, distribuir ou, de outra maneira, dispor inapropriadamente das funcionalidades do <span> https://www.portodevantagens.com.br. </span> </p>
<p><span> 2.2. Não mineração. </span> É vedado a utilização de softwares de mineração de dados do <span> https://www.portodevantagens.com.br</span>  , de qualquer tipo ou espécie, além de outro aqui não tipificado que atue de modo similar. </p>
<p><span> 2.3. Indenização. </span> Na incidência de danos à Porto rent a car ou a terceiros, o responsável se compromete a arcar com todas as obrigações de indenizar o sujeito lesado, inclusive aqueles cuja origem for de atos praticados por meio de sua Conta de Acesso, assumindo o polo passivo de ação judicial ou procedimento administrativo e requerendo a exclusão da Porto rent a car, devendo arcar totalmente com as despesas e custas processuais atinentes, deixando-a livre de prejuízos e ônus. </p>

<h3> 3. CONTEÚDO, DADOS SUBMETIDOS E PROPRIEDADE INTELECTUAL</h3>
<p><span> 3.1. Conteúdo. </span> Exceto se estabelecido em contrário por estes Termos, todas as informações, notícias, imagens, ilustrações, ícones, tecnologias, marcas e demais conteúdos audiovisuais ou sonoros, incluindo o software do<span>  https://www.portodevantagens.com.br </span> , disponibilizados em qualquer idioma ou forma, são de exclusiva propriedade da <span> Porto rent a car</span> ou licenciado por terceiros à <span> Porto rent a car</span>  (“Conteúdo”). A utilização do <span>https://www.portodevantagens.com.br</span>   não representa qualquer presunção transferência ou licença dessa propriedade. Por essa razão, <span> Você</span> não deverá comercializar no todo ou em parte o Conteúdo por quaisquer meios, onerosamente ou não, sabendo que se o fizer poderá ser penalizado civil e penalmente pela <span> Porto rent a car</span> e/ou por qualquer terceiro titular do Conteúdo. </p>
<p><span> 3.1.1. </span> A eventual remoção, bloqueio ou suspensão de qualquer Conteúdo ou funcionalidade do <span> https://www.portodevantagens.com.br </span> em decorrência de alguma reclamação, deverá ser sempre compreendida como demonstração de boa-fé e intenção de solução amigável de conflitos, jamais como reconhecimento de culpa ou de qualquer infração pela <span> Porto rent a car </span>a direito de terceiro. </p>
<p><span> 3.2. Seus Dados. Você</span> é e continuará sendo o titular e proprietário de todos os dados, informações, textos, imagens, mensagens ou qualquer outro material de qualquer forma for submetido e/ou compartilhado no <span> https://www.portodevantagens.com.br</span>  por <span>Você</span> (“Seus Dados”) bem como será o exclusivo responsável por eles, cabendo exclusivamente à <span> Você</span> o cuidado em respeitar a propriedade intelectual de terceiros ou quaisquer outros direitos conexos. </p>
<p><span> 3.3. Legalidade dos Seus Dados</span>. A<span>  Porto rent a car </span>não se obrigará a processar ou tratar quaisquer dos Seus Dados se houver razões para crer que tal processamento ou tratamento possa imputar à Porto rent a car qualquer infração de qualquer lei aplicável ou que o<span>  https://www.portodevantagens.com.br</span>  esteja sendo utilizado, sob critério exclusivo da <span> Porto rent a car</span>, para quaisquer fins ilegais, ilícitos ou contrários à moralidade. </p>
<p><span> 3.4. Ausência de garantias quanto a Seus Dados e ao Conteúdo. A Porto rent a car </span>não garante a qualidade, coerência, integridade, forma, atualização ou fonte do Conteúdo ou de Seus Dados, pois não controla, verifica ou faz juízo deste Conteúdo e de Seus Dados. A <span> Porto rent a car </span>não é responsável, portanto, por quaisquer inveracidade, desatualização ou erro deste Conteúdo ou de Seus Dados, bem como não é responsável por quaisquer danos oriundos deste Conteúdo, a qualquer título. </p>
<p><span> 3.4.1. Você</span> em nenhuma hipótese deverá tomar qualquer decisão, onerosa ou não, baseado integralmente no Conteúdo ou em qualquer funcionalidade do <span> https://www.portodevantagens.com.br</span> </p>
<p><span> 3.5. Armazenamento. </span>A <span>Porto rent a car</span> não presta e o <span> https://www.portodevantagens.com.br </span> não constitui serviço de armazenamento, portanto a <span> Porto rent a car</span> não possui qualquer obrigação de armazenar, reter ou fornecer à <span> Você </span>ou a quaisquer terceiros cópia de Seus Dados ou qualquer Conteúdo. </p>
<p><span> 3.6. Inteligência algorítmica. </span> O <span> https://www.portodevantagens.com.br</span> , de forma impessoal e automática, poderá aplicar modelos estatísticos e inteligência algorítmica para indexar, filtrar e organizar o Conteúdo ou Seus Dados, gerados ou compartilhados por meio do <span> https://www.portodevantagens.com.br</span> . </p>
<p><span> 3.6.1. Você </span>se declara ciente que a <span> Porto rent a car</span>, senão por seu exclusivo critério, não divulgará ou fornecerá à <span> Você</span> ou a qualquer terceiro quaisquer informações sistêmicas ou algorítmicas relacionadas ao <span> https://www.portodevantagens.com.br. </span></p>

<h3> 4. SUA PRIVACIDADE E SEUS DADOS PESSOAIS</h3>
<p><span> 4.1. Dados Pessoais. </span>Caso <span> Você</span> trate ou transmita no âmbito do <span> https://www.portodevantagens.com.br</span>  informações relativas a uma pessoa física identificada ou identificável (“Dados Pessoais”), <span> Você</span> será o exclusivo responsável por coletar as autorizações necessárias perante o titular dos Dados Pessoais. </p>
<p><span>  4.1.1. A Porto rent a car</span> monitorará, por meios adequados, sua própria conformidade com as respectivas obrigações de proteção de Dados Pessoais, caso aplicável. </p>
<p><span> 4.2. Registros</span>. A <span>Porto rent a car</span> poderá registrar todas as atividades efetuadas por <span> Você</span> no <span> https://www.portodevantagens.com.br</span>  ,incluindo dados de identificação, do dispositivo e da conexão utilizada (“Registros”). </p>
<p><span> 4.3. Finalidade da Coleta. </span> Os Registros poderão ser utilizados com a finalidade de: (i) identificar <span> Você</span> e atendê-lo (ii) cumprir as obrigações destes Termos (iii) aperfeiçoar o <span> https://www.portodevantagens.com.br</span>  ; (iv) resguardar direitos e obrigações relacionadas ao uso do <span> https://www.portodevantagens.com.br </span>  (v) cumprir ordem judicial e/ou de autoridade administrativa. </p>

<h3> 5. ISENÇÃO E LIMITAÇÕES DE RESPONSABILIDADE</h3>
<p><span> 5.1. </span> A Porto rent a car envida seus esforços para a manutenção da disponibilidade contínua e permanente do  <span> https://www.portodevantagens.com.br. </span> No entanto, pode ocorrer, eventualmente, alguma indisponibilidade temporária decorrente de manutenção necessária ou mesmo gerada por motivo de força maior, como desastres naturais, falhas nos sistemas de comunicação e acesso à Internet, ataques cibernético invasivos, ou quaisquer fatos de terceiro que fogem da esfera de vigilância e responsabilidade da <span> Porto rent a car. </span> </p>
<p><span> 5.1.1. </span>Se isso ocorrer, a <span> Porto rent a car</span> fará o que estiver ao seu alcance para restabelecer o acesso ao <span> https://www.portodevantagens.com.br</span>   o mais breve possível, dentro das limitações técnicas de seus serviços e serviços de terceiros, dos quais depende para ficar online. Por essa razão, Você fica ciente que não poderá pleitear indenização ou reparação de danos no caso de o <span> https://www.portodevantagens.com.br </span> permanecer fora do ar, independente da motivação. </p>
<p><span> 5.1.2. </span> Eventuais procedimentos de manutenção que acarretem a indisponibilidade do <span> https://www.portodevantagens.com.br</span>  por longos períodos serão informados por meio dos canais oficiais de comunicação da <span> Porto rent a car. </span></p>
<p><span>5.2. </span>Sem prejuízo de outras condições destes Termos, a <span> Porto rent a car </span>não se responsabiliza: </p>
<p><span>i. </span> Por quaisquer problemas, bugs, glitches ou funcionamentos indevidos que ocorrerem nos seus dispositivos e equipamentos; </p>
<p><span> ii. </span> Por qualquer dano direto ou indireto ocasionado por eventos de terceiros, a exemplo, mas não se limitando a ataque de hackers, falhas no sistema, no servidor ou na conexão à internet, inclusive por ações de softwares que possam, de algum modo, danificar seus ativos físicos ou lógicos em decorrência do acesso, utilização ou navegação no <span> https://www.portodevantagens.com.br</span>  , bem como a transferência de dados, arquivos, imagens, textos, áudios ou vídeos contidos no <span> https://www.portodevantagens.com.br</span>  ; </p>
<p><span> iii.</span> Pela sua navegação em quaisquer links externos disponibilizados no <span> https://www.portodevantagens.com.br</span> , sendo seus deveres a leitura dos Termos e Condições de Uso e da Política de Privacidade do recurso acessado e agir conforme o determinado; e</p>
<p>iv. Por verificar, controlar, aprovar ou garantir a adequação ou exatidão das informações ou dados disponibilizados em tais links, não sendo, portanto, responsáveis por prejuízos, perdas ou danos ocorridos pela visita de tais sites, cabendo ao interessado verificar a confiabilidade das informações e dados ali exibidos antes de tomar alguma decisão ou praticar algum ato. </p>
<h3> 6. OUTRAS DISPOSIÇÕES</h3>
<p><span> 6.1. Canais de Atendimento. Você </span>poderá utilizar os <span> Canais de Comunicação</span> disponibilizados no  <span> https://www.portodevantagens.com.br</span>  toda vez que tiver alguma dúvida, sugestão ou reclamação, seja sobre o <span>https://www.portodevantagens.com.br</span>  ou sobre estes Termos. </p>
<p><span> 6.2. Atualização dos Termos. </span> Estes Termos estão sujeitos a constante melhoria e aprimoramento. Assim, a <span> Porto rent a car</span> se reserva o direito de modificá-los a qualquer momento, conforme sua finalidade ou conveniência, tal qual para adequação e conformidade legal de disposição de lei ou norma que tenha força jurídica equivalente, incluindo de órgãos reguladores, ou seja, <span>Você</span> deverá verificá-lo sempre que efetuar o acesso no <span>https://www.portodevantagens.com.br</span> </p>
<p><span> 6.2.1. </span> Ocorrendo atualizações nestes Termos, a<span>  Porto rent a car</span> notificará <span>Você</span> pelas ferramentas disponíveis no <span> https://www.portodevantagens.com.br </span> ou pelos meios de contato fornecidos por <span>Você. </span></p>
<p><span> 6.2.2. </span> Ao navegar pelo <span> https://www.portodevantagens.com.br</span>  e utilizar suas funcionalidades, <span> Você </span>aceita guiar-se pelos Termos que se encontram vigentes na data de acesso. Por isso, é recomendável que <span>Você</span> se mantenha atualizado das condições vigentes. </p>
<p><span> 6.3. Novação e renúncia. </span>A tolerância do eventual descumprimento de quaisquer condições destes Termos não constituirá renúncia ou novação nem impedirá a <span> Porto rent a car</span> de exigir estas condições a qualquer tempo. </p>
<p><span> 6.4. Nulidade. </span> Se alguma disposição destes Termos for julgada inaplicável ou sem efeito, o restante continuará a viger normalmente. </p>
<p><span> 6.5. Comunicação. Você </span>reconhece que toda comunicação realizada por e-mail (ao endereço de e-mail informado no seu cadastro) é válida, eficaz e suficiente para a divulgação de qualquer assunto que se refira ao <span> https://www.portodevantagens.com.br</span> </p>
<p><span> 6.6. Data e hora. </span>O <span> https://www.portodevantagens.com.br</span>  tem como base a data e horários oficiais de Brasília (UTC/GMT -03:00). </p>
<p><span> 6.7. Lei aplicável e foro. </span> Estes Termos serão interpretados segundo a legislação brasileira, no idioma português, e fica eleito o foro da Comarca da comarca do seu domicílio (<span> Você</span>) para dirimir qualquer controvérsia, salvo se a legislação aplicável ressalvar especificamente outra competência pessoal, territorial ou funcional. </p>

<h3> 7. GLOSSÁRIO</h3>
<p><span> v. Porto D & R Locadora de Veiculos Ltda, </span> pessoa jurídica de direito privado, com sede na Rua Raul Veiga, 389, Loja 28 , Centro , Cabo Frio , Estado do Rio de Janeiro, inscrita no CNPJ/MF sob nº 41.341.666/0001-90. </p>
<p><span> vi. https://www.portodevantagens.com.br: </span> Ferramenta online, disponibilizada pela Porto rent a car para o site consiste em uma plataforma para que os usuários conheçam a Porto rent a car, obtenham informações sobre as particularidades do negócio e acessem documentos relevantes. </p>
<p><span> vii. Anti-Spam: </span>Sistema que evita correspondências não desejadas, como publicidade em massa, pelo bloqueio de mensagens ou as movendo para pasta específica. </p>
<p><span> viii. Canais de Comunicação: </span> Telefone <span> 22 3031-4272. </span> </p>
<p><span> ix. Layout: </span> Conjunto compreendido entre aparência, design e fluxos do <span> https://www.portodevantagens.com.br</span> . </p>
<p><span> x. Link: </span> Terminologia para endereço de internet. </p>

        </div>
                </div>
            </div>
                <Footer />
        </div>

    )
}

export default TermsOfUsePage;